Repository QuivrHQ/MegaParse, pull requests merged in 2025-02, with the labels that each got.

#227 chore(main): release megaparse 0.0.54
  .release-please-manifest.json
  libs/megaparse/CHANGELOG.md
  libs/megaparse/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S, lgtm

#204 chore(main): release megaparse-sdk 0.1.11
  .release-please-manifest.json
  libs/megaparse_sdk/CHANGELOG.md
  libs/megaparse_sdk/pyproject.toml
Labels: autorelease: pending, size:S, lgtm

#228 feat: add layout detection
  libs/megaparse_sdk/megaparse_sdk/schema/mp_outputs.py
Labels: enhancement, size:XS

#229 chore(main): release megaparse-sdk 0.1.12
  .release-please-manifest.json
  libs/megaparse_sdk/CHANGELOG.md
  libs/megaparse_sdk/pyproject.toml
Labels: autorelease: pending, autorelease: tagged, size:S, lgtm

#230 feat: remove tensorrt
  libs/megaparse/src/megaparse/examples/parsing_process.py
  libs/megaparse/src/megaparse/parser/doctr_parser.py
  libs/megaparse/src/megaparse/utils/onnx.py
Labels: enhancement, size:M, lgtm

#231 chore(main): release megaparse 0.0.55
  .release-please-manifest.json
  libs/megaparse/CHANGELOG.md
  libs/megaparse/pyproject.toml
Labels: autorelease: pending, size:S, lgtm

#234 fix: fix logging message
  libs/megaparse/src/megaparse/utils/onnx.py
Labels: size:XS, lgtm
