Repository QuivrHQ/MegaParse, pull requests merged in 2025-01, with the labels that each got.

#218 fix: logging error
  libs/megaparse/src/megaparse/parser/doctr_parser.py
Labels: size:XS, lgtm

#216 feat: type strategy output
  README.md
  benchmark/process_single_doc.py
  evaluations/script.py
  libs/megaparse/src/megaparse/api/app.py
  libs/megaparse/src/megaparse/configs/auto.py
  libs/megaparse/src/megaparse/examples/parse_file.py
  libs/megaparse/src/megaparse/examples/parsing_process.py
  libs/megaparse/src/megaparse/megaparse.py
  libs/megaparse/src/megaparse/models/page.py
  libs/megaparse/src/megaparse/parser/base.py
  libs/megaparse/src/megaparse/parser/doctr_parser.py
  libs/megaparse/src/megaparse/parser/strategy.py
  libs/megaparse/src/megaparse/predictor/doctr_layout_detector.py
  libs/megaparse/src/megaparse/predictor/models/base.py
  libs/megaparse/src/megaparse/utils/strategy.py
  libs/megaparse/tests/pdf/test_all_parsers.py
  libs/megaparse/tests/pdf/test_detect_ocr.py
  libs/megaparse/tests/pdf/test_pdf_processing.py
  libs/megaparse/tests/test_import.py
  libs/megaparse/tests/test_parsers.py
Labels: enhancement, size:XXL, lgtm

#197 chore(main): release megaparse 0.0.53
  .release-please-manifest.json
  libs/megaparse/CHANGELOG.md
  libs/megaparse/pyproject.toml
Labels: autorelease: pending, size:S
